baseURL: "https://nizihan29.github.io/" 
title: Zihan Ni
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 1
        - name: Pubs
          url: pubs/
          weight: 2
        - name: Research
          url: research/
          weight: 3
        - name: Wiki
          url: https://en.wikipedia.org
          weight: 4

params:
    description: "This website hosts Zihan Ni's research papers, data, curriculum vitae, and contact information."
    author: Zihan Ni
    googleAnalyticsID: "G-MHNMJDWTNX"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    # mainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zihan Ni
          subtitle: <b>(This page is under construction)</b> Welcome! I am <b>Zihan Ni</b>, currently a Master's student at <a href="https://www.kyoto-u.ac.jp/" class="school-link" target="_blank" rel="noopener noreferrer">Kyoto Uni.</a> My recent research interests lie in <span class="highlight-text">Applied Machine Learning</span> and <span class="highlight-text">Representation Learning</span>. Beyond academia, I am an avid fan of anime. <br><br>
          imageUrl: "avatar.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Pubs
              url: pubs/
            - name: Research
              url: research/
            - name: Wiki
              url: https://en.wikipedia.org/

    socialIcons:
        - name: CV
          url: CV_en.pdf
        - name: Email
          url: mailto:nizihan29@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/zihan-n-baa39636a
        - name: GitHub
          url: https://github.com/nizihan29
        - name: X
          url: https://x.com/m1n645372

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zihan Ni"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
